### ISSUE TITLE
Create condition for an entity

### ISSUE THREAD

**Issue by Sandy-at-Tazama** [frmscoe/admin-service#41]
## Story statement
As a Fraud Administrator,
**I want** to be able to add a new condition for an entity
**So that** the system is able to block or override a transaction event based on the evaluation of conditions against one of the transaction event attributes AND 
**So that** the system can exert operational control over evaluations based on the outcome of business processes and prior evaluations

## Description / Overview
New functionality is being added to the Tazama system to be able to block or allow a transaction event based on the evaluation of conditions against one of the transaction event attributes. The purpose of this user story is to provide a feature to allow a user to create a condition for an entity via an Admin API.

See epic: https://github.com/frmscoe/tazama-project/issues/12

## Sequence diagram
```mermaid
sequenceDiagram
  participant clientsystem as Client System
  participant tmsapi as Admin API
  participant cache as Cache
  participant db as Database

  clientsystem->>tmsapi: setCondition()
  tmsapi->>db: setCondition()
  db->>tmsapi: writeOK(recordId)
  tmsapi->>cache: setCondition()
  cache->>tmsapi: writeOK()
  tmsapi->>clientsystem: writeOK(recordId)
```
## Acceptance criteria
1. Create an administrative API that has access to the Tazama database
   1. recommended `/v1/admin/event-flow-control/entity`
2. Create REST (POST) endpoint to allow a client system to add a condition in the Tazama graph database for an entity
3. If the system is unable to write to the database, retry 5 times, if still unable to write, return error. 

## Message format 
```JSON
{
    "evtTp": [
        "pacs.008.01.10",
        "pacs.002.01.11"
    ],
    "condTp": "non-overridable-block",
    "prsptv": "both",
    "incptnDtTm": "2024-01-01T24:00:00.999Z",
    "xprtnDtTm": "2024-03-03T24:00:00.999Z",
    "condRsn": "R001",
    "ntty": {
        "id": "+27730975224",
        "schmeNm": {
            "prtry": "MSISDN"
        }
    },
    "forceCret": true,
    "usr": "bob"
}
```

## Functional requirements
1. The event type `evtTp` is mandatory and must be an array containing one or more of the current list of values `pacs.002.01.11`, `pacs.008.01.11`, `pain.001.01.11`, `pain.013.01.11`, OR `all`. The event type `evtTp` must be validated in the API via fastify ajv.
2. The condition type `condTp` is mandatory and must be one of `non-overridable-block` or `overridable-block` or `override` and must be validated in the API via fastify ajv. 
3. The block perspective `prsptv` is mandatory and must be one of `creditor`, `debtor` or `both` and must be validated in the API via fastify ajv.
4. Inception date `incptnDtTm` is optional for all condition types
   1. If `incptnDtTm` date is not provided, it must default to NOW
   2. If `incptnDtTm` date is provided, it must be greater than NOW
5. Expiration date `xprtnDtTm` is mandatory for `override` conditions
   1. `xprtnDtTm` date must be after `incptnDtTm` 
6. Expiration date `xprtnDtTm` is optional for `non-overridable-block` or `overridable-block` conditions
   1. If `xprtnDtTm` is not provided (omitted or `null`), it must be omitted in the database.
   2. If provided,
      1. `xprtnDtTm` date must be after `incptnDtTm` 
7. Reason code `condRsn` is mandatory.
8. The entity identifier `ntty` object and its contents are mandatory. The structure of the entity identifier is based on that of an element of a debtor or creditor entity in an ISO20022 message. Ref https://github.com/frmscoe/tms-service/issues/154. 
    1. If the entity node exists, create the condition and edge.
    2. If the entity node does not exist in the database and `forceCret` is true, create the entity in the database, create condition and edge.
    3. If the entity node does not exist in the database and `forceCret` is false or omitted, fail and respond with an error.
9. Create an edge that describes whether the condition is for a debtor or creditor `prsptv` (or both, if specified) as `governed_as_debtor_by` or `governed_as_creditor_by`
10. User `usr` is mandatory (for audit purposes): if null, return an error message.
11. Create date `creDtTm` must be set to NOW() (javascript function) by the API on receipt and processing of the request.

## Complete Success Criteria
1. The condition is stored in a new `conditions` collection in the `pseudonyms` database (as part of the history graph) and available for future retrieval
2. If successfully written to the DB, the condition is also stored in Valkey (https://valkey.io/) cache for high speed retrieval (i.e. write-aside caching). Also consider gremlin tinkerpop for in memory graph option
3. The document for the new condition must be structured as follows (sample):
    ```JSON
    {
      "condTp": "non-overridable-block",
      "incptnDtTm": "2024-01-01T24:00:00.999Z",
      "xprtnDtTm": "2024-03-03T24:00:00.999Z",
      "condRsn": "R001",
      "usr": {bob},
      "creDtTm": "2024-01-01T24:00:00.999Z"
    }
    ```
4. The condition is assigned a unique identifier `condId` by the database when the document is created.
5. The condition type `condTp` will be either `non-overridable-block` or `overridable-block` or `override`
6. The condition contains an inception date `incptnDtTm`
7. The condition may contain an expiration date `xprtnDtTm` (if provided). If no `xprtnDtTm` is provided, this attribute is omitted
8. The condition contains a `condRsn` reason code
9. The condition contains the `usr` that created it via the API
10. The create date `creDtTm` is set to the ISO8601 timestamp with 0 (zero) off-set for the time at which the request was received and processed
11. The entity to which the condition applies is linked to the condition with one or two edges, depending on the value of the `prsptv` attribute in the payload:
    1. For `prsptv` = "both", create both of the following edges, otherwise just create the one indicated.
    2. For `prsptv` = "debtor", create an edge from the entity to the condition called `governed_as_debtor_by`.
    3. For `prsptv` = "creditor", create an edge from the entity to the condition called `governed_as_creditor_by`.
12. The document for the new edge(s) must be structured as follows:
    ```JSON
    {
      "evtTp": ["pacs.008.01.10", "pacs.002.01.11"],
      "incptnDtTm": "2024-01-01T24:00:00.999Z",
      "xprtnDtTm": "2024-03-03T24:00:00.999Z"
    }
    ```
13. Event types are defined by the `evtTp` attribute or all event types are defined by `evtTp = ["all"]`  
14. The edge contains an inception date `incptnDtTm`
15. The edge contains an expiration date `xprtnDtTm` (only if provided)
16. If the entity node exists, create the condition and edge.
17. If the entity node does not already exist in the database and `forceCret` is true, create the entity in `entities` collection in the `pseudonyms` DB
    - If `forceCret` is false, return an error to indicate the entity required does not exist in the database
18. If there are active conditions i.e. conditions that have not yet expired (i.e. it has no expiry date or the expiry date is after now), then return a warning `conditions already exist for the entity` and return all active conditions and edges (Using the retrieve condition function with the active parameter)

**Success response**
200 OK

**Error responses**      
4xx
5xx

**Comment by cshezi** [comment]
This issue is blocked by the central library PR which is waiting for the documentation merge
central lib PR: https://github.com/frmscoe/frms-coe-lib/pull/152

**Comment by cshezi** [comment]
coe-lib documentation was updated https://github.com/frmscoe/frms-coe-lib/pull/153

**Comment by Sandy-at-Tazama** [comment]
**condId** should be the database **_key**
