### ISSUE TITLE
BUG: new condition for entity - governed_as_creditor_by edge _ID

### ISSUE THREAD

**Issue by Sandy-at-Tazama** [frmscoe/admin-service#64]
Acceptance Criteria: Condition edges must be assigned unique identifier by the database 

Condition unique id assigned by the database:
![image](https://github.com/user-attachments/assets/da7ce857-3207-476e-9030-7c94ddd1d826)

Condition edges unique ID should be assigned by the database and not made up of condition id and entity id/ prtry:
![image](https://github.com/user-attachments/assets/215db8e3-ff16-4612-a0b6-118e6cabec66)

https://github.com/frmscoe/admin-service/issues/47 
https://github.com/frmscoe/admin-service/issues/41

Please also check account edges

**Comment by rtkay123** [comment]
This should be done. Fixed with the PR that is linked.

**Comment by Sandy-at-Tazama** [comment]
Change was on coe-lib
