### ISSUE TITLE
BUG: conditions already exist for the entity

### ISSUE THREAD

**Issue by Sandy-at-Tazama** [frmscoe/admin-service#66]
Success criteria from https://github.com/frmscoe/admin-service/issues/41
#18 If there are active conditions i.e. conditions that have not yet expired (i.e. it has no expiry date or the expiry date is after now), then return a warning `conditions already exist for the entity' and return all active conditions and edges (Using the retrieve condition function with the active parameter)

There is an anomaly in the response when creating a second condition against the same entity. When we  create the first condition, the response returns the condition we just created, but when we created the second condition, the response only returns the first condition, and not the second condition.  At the time when the first condition is created, there are no existing conditions and no warning should be returned. From the second condition onwards, there should be a warning `conditions already exist for the entity'  and return **ALL** active conditions and edges

**Comment by cshezi** [comment]
This issue ticket specifies that the response body should be aligned with the GET requests to ensure consistent replies of the service, This alignment added:

1. Usage of active filter which was found with a bug.
2. Usage of parsing of graph data.
3. Updated response type
4. Separation of unit tests for context
5. Alignment of cache keys

**Comment by Sandy-at-Tazama** [comment]
Tested and confirmed fixed
